# 50 NUMPY FUNCTIONS AND ITS APPLICATION

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.4'

In [3]:
!pip install --user --upgrade numpy 

In [4]:
np.__version__

'1.19.4'

In [5]:
# Difference between %time and %timeit

#%time calculate time used for running any code
#%timeit runs the code again and again and calculated time on total and each iteration and also gives standard deviation

In [6]:
%time [i for i in range (2000000)][:10]


Wall time: 367 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
%timeit [i for i in range (2000000)][:9]


353 ms ± 26.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%run name.py

Name: Urslan Ali
PIAIC Roll No. PIAIC150274
Batch 34


In [9]:
%time a = np.arange(100000)+5
a[:5]

Wall time: 738 µs


array([5, 6, 7, 8, 9])

In [10]:
l = [x for i in range(3)
    for x in range(3)]
l

[0, 1, 2, 0, 1, 2, 0, 1, 2]

In [11]:
a = [[1,2,3,4],
     [5,6,7,8],
    [9,10,11,12]]
a

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [12]:
[i[0] for i in enumerate(a)]
a

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [13]:
for i in enumerate(a):
    for c in enumerate(a[i[0]]):
        a[i[0]][c[0]] += 1
%time
a

Wall time: 0 ns


[[2, 3, 4, 5], [6, 7, 8, 9], [10, 11, 12, 13]]

In [14]:
l1 = np.arange(1,10)
l1 = l1.reshape(3,3)
l1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
l1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
l2 = np.arange(2*2).reshape(2,2)
l2

array([[0, 1],
       [2, 3]])

In [17]:
np.arange(2*2)

array([0, 1, 2, 3])

In [18]:
l3 = np.arange(3*3*3).reshape(3,3,3)
l3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [19]:
type(l3)

numpy.ndarray

In [20]:
l = [1,1,2,3]
l4 = np.array(l)
print(type(l4))
type(l)

<class 'numpy.ndarray'>


list

In [21]:
l = [1,1,2,3]
l4 = np.asarray(l).reshape(2,2)
type(l4)


numpy.ndarray

In [22]:
# difference between array and asarray
# - array will make copy by default of given input
# - asarray will not make copy by default if input type is compatible ndarray.

In [23]:
# The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension
np.shape(l4)


(2, 2)

In [24]:
print(l4[0])

[1 1]


# 1D array, 2D array, ndarray, vector, matrix

In [25]:
# ndarray is a claa of numpy library (N Dimensiontional Array)
# An array is usually a fixed-size container of items of the same type and size.
# The NumPy ndarray class is used to represent both matrices and vectors.
# Vector is an array with a single dimension 
# Matrix refers to an array with two dimensions
# 3-D or higher dimensional arrays, the term tensor is also commonly used.
# The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.
# In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:
# [[0., 0., 0.],
# [1., 1., 1.]]
# different arrays can share the same data, so changes made on one array might be visible in another.


# np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [26]:
np.array(([1,2,3,4],[5,6,7,8]))
np.shape(np.array(([1,2,3,4],[5,6,7,8])))


(2, 4)

In [27]:
np.zeros((4,4)), np.zeros(3)

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([0., 0., 0.]))

In [28]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.empty((3,3)), np.empty(2)

(array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 5.77068674e-321],
        [1.05699242e-307, 3.11523242e-307, 1.59167509e-308]]),
 array([0., 0.]))

In [30]:
np.arange(2,9,4), np.arange(2,9,2), np.arange(4)

(array([2, 6]), array([2, 4, 6, 8]), array([0, 1, 2, 3]))

In [31]:
np.linspace(2,20, num=7), np.linspace(1,20, num=3)

(array([ 2.,  5.,  8., 11., 14., 17., 20.]), array([ 1. , 10.5, 20. ]))

In [32]:
# the default data type is floating point (np.float64), it can self defined as well dtype=np.int16
x = np.ones((2,2,2,2), dtype=np.int16)
x

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]], dtype=int16)

In [33]:
np.size(x), np.shape(x)

(16, (2, 2, 2, 2))

# Adding, removing, and sorting elements¶


In [34]:
np.sort([2,"d",4,"t"])

array(['2', '4', 'd', 't'], dtype='<U11')

In [35]:
z = np.array([9,2,4,1,7,9,10,11,12,13,14,15,90,91,99,98]).reshape(2,2,2,2)
np.argsort(z, axis=-1, kind=None, order=None)

array([[[[1, 0],
         [1, 0]],

        [[0, 1],
         [0, 1]]],


       [[[0, 1],
         [0, 1]],

        [[0, 1],
         [1, 0]]]], dtype=int64)

In [36]:
np.concatenate((x,z), axis=0), np.concatenate((x,z), axis=1), np.concatenate((x,z), axis=-1)

(array([[[[ 1,  1],
          [ 1,  1]],
 
         [[ 1,  1],
          [ 1,  1]]],
 
 
        [[[ 1,  1],
          [ 1,  1]],
 
         [[ 1,  1],
          [ 1,  1]]],
 
 
        [[[ 9,  2],
          [ 4,  1]],
 
         [[ 7,  9],
          [10, 11]]],
 
 
        [[[12, 13],
          [14, 15]],
 
         [[90, 91],
          [99, 98]]]]),
 array([[[[ 1,  1],
          [ 1,  1]],
 
         [[ 1,  1],
          [ 1,  1]],
 
         [[ 9,  2],
          [ 4,  1]],
 
         [[ 7,  9],
          [10, 11]]],
 
 
        [[[ 1,  1],
          [ 1,  1]],
 
         [[ 1,  1],
          [ 1,  1]],
 
         [[12, 13],
          [14, 15]],
 
         [[90, 91],
          [99, 98]]]]),
 array([[[[ 1,  1,  9,  2],
          [ 1,  1,  4,  1]],
 
         [[ 1,  1,  7,  9],
          [ 1,  1, 10, 11]]],
 
 
        [[[ 1,  1, 12, 13],
          [ 1,  1, 14, 15]],
 
         [[ 1,  1, 90, 91],
          [ 1,  1, 99, 98]]]]))

In [37]:
# concatination of two different dimentional arrays

g = np.array([[1,3],[2,3]])
y = np.array([[7,8]])
np.concatenate([g,y], axis=0)

array([[1, 3],
       [2, 3],
       [7, 8]])

In [38]:
np.shape(y), np.shape(g)

((1, 2), (2, 2))

In [39]:
# ndarray.ndim, ndarray.size, ndarray.shape
# ndarray.ndim will tell you the number of axes, or dimensions, of the array.
# ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.
# ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).


In [40]:
b = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],
               [[0, 1, 2, 3],
                [4, 5, 6, 7]],
               [[0 ,1 ,2, 3],
                [4, 5, 6, 7]]])
b

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [41]:
b.ndim

3

In [42]:
b.size

24

In [43]:
b.shape

(3, 2, 4)

In [44]:
f = np.arange(6)
f.ndim, f.size, f.shape

(1, 6, (6,))

In [45]:
b.reshape(6,4), b.reshape(8,3), b.reshape(2,2,6)

(array([[0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 0],
        [1, 2, 3],
        [4, 5, 6],
        [7, 0, 1],
        [2, 3, 4],
        [5, 6, 7]]),
 array([[[0, 1, 2, 3, 4, 5],
         [6, 7, 0, 1, 2, 3]],
 
        [[4, 5, 6, 7, 0, 1],
         [2, 3, 4, 5, 6, 7]]]))

In [46]:
np.reshape(f, newshape=(2,3), order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
a = np.arange(4) 
print(a.shape) #1D   
a1 =a[np.newaxis, :] # It will add colums
print(a1.shape) # 2D
print(a,a1)
a2 =a1[np.newaxis, :]
print(a2.shape) # 3D
a2

(4,)
(1, 4)
[0 1 2 3] [[0 1 2 3]]
(1, 1, 4)


array([[[0, 1, 2, 3]]])

In [48]:
a3=a[:, np.newaxis] # adding rows vector
a3.shape
a3

array([[0],
       [1],
       [2],
       [3]])

In [49]:
c = np.arange(1,7)
c.shape

(6,)

In [50]:
c1 = np.expand_dims(c, axis=1)
c1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Indexing and slicing

In [51]:
c

array([1, 2, 3, 4, 5, 6])

In [52]:
print(c[0], c[0:], c[:4], c[:],c[-2:], sep="\n")

1
[1 2 3 4 5 6]
[1 2 3 4]
[1 2 3 4 5 6]
[5 6]


In [53]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a = a*2
print(a)
print(a[a<9])
print(a[a<=9])
print(a[a>=9])
five = (a>5)
modulous = (a%2==0)
print(a[five])
print(a[modulous])
cg = a[(a>4) & (a<14)]
print(cg)
cf = (a>4) | (a==4)
print(cf)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[2 4 6 8]
[2 4 6 8]
[10 12 14 16 18 20 22 24]
[ 6  8 10 12 14 16 18 20 22 24]
[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 6  8 10 12]
[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [54]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
b = np.nonzero(a < 5) = #used to print indices of values in array matching condition.
print(b)

#first array is showing row index and second arrange is showing column index where values are found.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [55]:
# slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [56]:
# slicing
n = a[0:4]
n

array([1, 2, 3, 4])

In [58]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])

In [59]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [60]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [62]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [63]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [65]:
np.vsplit(x, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [66]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [68]:
# You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy).
# modifying data in a view also modifies the original array!
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
b1 = a[0,:]
b1

array([1, 2, 3, 4])

In [70]:
b1[0] = 99
b1


array([99,  2,  3,  4])

In [71]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
# Using the copy method will make a complete copy of the array and its data (a deep copy). Any change made to a copy will not change original array.
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
b2[0] = 0
print(b2)
print(a)

[[ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
data = np.array([1,2])
ones =np.ones(2)
data , ones

(array([1, 2]), array([1., 1.]))

In [78]:
print(data + ones) # it will each elements on same index
print(data / ones)
print(data * ones)
print(data % ones)

[2. 3.]
[1. 2.]
[1. 2.]
[0. 0.]


In [79]:
# Getting total of all elements
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.sum()

78

In [80]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)  # to get sum of row


array([3, 3])

In [81]:
b.sum(axis=1) # to get sum of colum

array([2, 4])

In [83]:
# Broadcasting :here are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes

data = np.array([1.0, 2.0])
data*2

array([2., 4.])

In [84]:
# maximum, minimum, sum, mean, product, standard deviation


In [85]:
data.max()

2.0

In [86]:
data.min()

1.0

In [87]:
data.std()

0.5

In [88]:
data.prod()

2.0

In [89]:
data.mean()

1.5

In [90]:
data.sum()

3.0

In [104]:
a = np.array([[1,2], [5,4], [3,6]])
a

array([[1, 2],
       [5, 4],
       [3, 6]])

In [99]:
a[0,1]

2

In [100]:
a[1:3]

array([[3, 4],
       [5, 6]])

In [101]:
a[0:2,0]

array([1, 3])

In [105]:
a.max(axis=0),a.max(axis=1) 

(array([5, 6]), array([2, 5, 6]))

In [108]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 2]])

In [109]:
data + ones_row

array([[2, 4],
       [4, 6],
       [6, 8]])

In [110]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [113]:
print(np.ones(3))
print(np.zeros(3))
rng = np.random.default_rng(0)
rng.random(3)

[1. 1. 1.]
[0. 0. 0.]


array([0.63696169, 0.26978671, 0.04097352])

In [114]:
rng.integers(5, size=(2, 4))

array([[0, 0, 0, 4],
       [3, 4, 2, 3]], dtype=int64)

In [115]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [116]:
# to get indices of uniques in a array
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [117]:
# to return count of unique
np.unique(a, return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [118]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
np.unique(a_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
np.unique(a_2d, axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
np.unique(a_2d, axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [122]:
a_2d.transpose()

array([[ 1,  5,  9,  1],
       [ 2,  6, 10,  2],
       [ 3,  7, 11,  3],
       [ 4,  8, 12,  4]])

In [124]:
a_2d.T

array([[ 1,  5,  9,  1],
       [ 2,  6, 10,  2],
       [ 3,  7, 11,  3],
       [ 4,  8, 12,  4]])

In [125]:
np.flip(a_2d) # to reverse the contents

array([[ 4,  3,  2,  1],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])